name: Variables Demo

on:
  workflow_dispatch:

env:
  COMPANY: NWORKIT

jobs:
  variables:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Company = $COMPANY"

      - name: Secret Example
        run: |
          echo "Secret exists"
        env:
          API_KEY: ${{ secrets.API_KEY }}